### ISSUE TITLE
Error after downloading

### ISSUE THREAD

**Issue by viktor02** [Xealeph/Yiff.party-Image-Scraper#1]
```
Traceback (most recent call last):
  File "yiff_image_scraper.py", line 100, in <module>
    downloadImages(url, urlCounter)
  File "yiff_image_scraper.py", line 94, in downloadImages
    print("\nSuccessfully downloaded " + str(len(imageCounter)) + " Images!\n")
TypeError: object of type 'int' has no len()
```

**Comment by Xealeph** [comment]
fixed it!
thank you for pointing it out
