### ISSUE TITLE
'list' referenced before assingment (due to Fantia?)

### ISSUE THREAD

**Issue by Ruthalas** [Xealeph/Yiff.party-Image-Scraper#17]
I tried running the current version on a patreon yiff.party, and it failed at line 324 when it tries to reference the variable _list_, which I think (?) has not been set because the link used is not on the Fantia platform.
234:
```
    if platform != 'fantia':
        linkList = list(dict.fromkeys(linkList))
```
If the link _is_ Fantia, that variable gets set at line 251:
```
if platform == 'fantia':
            list = []
            containersFantia = soup.find_all('div', {'class': 'col s12 m6'})
            for cont in containersFantia:
                list.append("https://yiff.party" + cont.a['href'].strip())
                linkList += fantiaSubroutine(list)
            continue
```
But if the platform is not Fantia, the variable is never initialized, I think.

This is the output:
```
======Starting Scraper========
Traceback (most recent call last):
  File "yiff_image_scraper.py", line 437, in <module>
    downloadImages(url, urlCounter, useFolders)
  File "yiff_image_scraper.py", line 324, in downloadImages
    linkList = list(dict.fromkeys(linkList))
UnboundLocalError: local variable 'list' referenced before assignment
```

**Comment by Xealeph** [comment]
Thank you!
The bug should be fixed now.
