### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by HydroHydro** [Xealeph/Yiff.party-Image-Scraper#21]
Thanks so much for the database! Looks like it's working perfectly!

In the process of using the new update, it seems I've found a bug.

Tried to get this: https://yiff.party/fantia/21000
(NSFW)

And got this error:

Traceback (most recent call last):
  File "yiff_image_scraper.py", line 490, in <module>
    downloadImages(url, urlCounter, useFolders)
  File "yiff_image_scraper.py", line 392, in downloadImages
    f.writelines(galleryAuthor + '\n;')
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u3072' in position 0: character maps to <undefined>

**Comment by Xealeph** [comment]
Fixed it!
